# Tell Travis CI we are using PHP
language: php

# The platforms you wants to test on
os:
  - linux

# Define the php versions against we want to test our code
php:
    - 5.6
env:
- DB_HOST=localhost DB_DATABASE=mysql DB_USERNAME=root DB_PASSWORD=''

dist: trusty
sudo: required
addons:
  packages:
    - unzip

# Disable x-debug to speed up things
before_install: phpenv config-rm xdebug.ini

# Install packages those will be required during build
install:
# Install dependencies.
- sudo apt-get update
- sudo apt-get install -y openjdk-8-jre-headless xvfb libxi6 libgconf-2-4

# Install Chrome.
- wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P ~/
- sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb
- sudo apt-get -f install -y
- sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb

# Install ChromeDriver.
- wget -N http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

# Install Selenium.
- wget -N http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar -P ~/
- sudo mv -f ~/selenium-server-standalone-3.0.1.jar /usr/local/share/
- sudo chmod +x /usr/local/share/selenium-server-standalone-3.0.1.jar
- sudo ln -s /usr/local/share/selenium-server-standalone-3.0.1.jar /usr/local/bin/selenium-server-standalone-3.0.1.jar

#- "export DISPLAY=:99.0"
#- "sh -e /etc/init.d/xvfb start"


# Prepare test environment
before_script:
  - 'nohup  xvfb-run java -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -jar /usr/local/bin/selenium-server-standalone-3.0.1.jar &'
  - sleep 3 # give xvfb some time to start
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


# Run main commands
script:
  - mkdir bootstrap/cache
  - mkdir storage
  - mkdir storage/app
  - mkdir storage/framework
  - mkdir storage/framework/sessions
  - mkdir storage/framework/cache
  - mkdir storage/framework/views
  - chmod 777 -R storage
  - composer install --no-interaction
  - php artisan migrate --force
  - php artisan serve &
  - sleep 3
  - sudo /etc/init.d/mysql start
  - sleep 3
  - sudo start apache2
  - sleep 3
  - vendor/bin/codecept build
  - sleep 3
  - vendor/bin/codecept run tests/acceptance --steps --debug

#after_script:

#after_success:

#after_failure:


# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

