addons:
    hosts:
        - localhost
sudo: false

language: php

php:
  - 5.6
env:
- DB_HOST=localhost DB_DATABASE=mysql DB_USERNAME=root DB_PASSWORD=''

before_script:
  - chmod -R 777 storage
  - composer install --no-interaction
  - php artisan migrate --force
  - php artisan serve --port=8000 --host=localhost &
  - sleep 5
  - java -jar seleniumjar.jar -Dwebdriver.chrome.driver=./chromedriver

script:
  - vendor/bin/codecept run tests/acceptance --steps