language: php

php:
  - 5.6
env:
- DB_HOST=localhost
- DB_DATABASE=mysql
- DB_USERNAME=root
- DB_PASSWORD=''

before_script:
  - composer install --no-interaction
  - php artisan migrate --force
  - php artisan serve
  - java -jar seleniumjar.jar -Dwebdriver.chrome.driver=./chromedriver

script:
  - vendor/bin/codecept run tests/acceptance --steps