# Tell Travis CI we are using PHP
language: php

# The platforms you wants to test on
os:
  - linux

#addons

# git configs
git:
  depth: 1

# Define the php versions against we want to test our code
php:
    - 5.6
env:
- DB_HOST=localhost DB_DATABASE=mysql DB_USERNAME=root DB_PASSWORD=''


# We don't want to run linux commands as super user
#false means Travis will run this in a container
sudo: false

# Disable x-debug to speed up things
before_install: phpenv config-rm xdebug.ini

# Install packages those will be required during build
install:
  - composer install --no-interaction
  - php artisan migrate --force
  - php artisan serve --port=8000 --host=localhost &
  - sleep 5


# Prepare test environment
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - echo "Download selenium-server-standalone jar file"
  - wget -c -nc --retry-connrefused --tries=0 http://goo.gl/EoH85x -O selenium-server-standalone.jar
  - sudo apt-get install unzip
  - wget -N http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip -P ~/Downloads
  - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
  - chmod +x ~/Downloads/chromedriver
  - sudo mv -f ~/Downloads/chromedriver /usr/local/share/chromedriver
  - echo Change the directory to /usr/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
  - echo "Run selenium server - background process"
  - nohup bash -c "java -jar selenium-server-standalone.jar &" && sleep 1; cat nohup.out
  - echo "Run php in-built server - background process"
  - nohup bash -c "php -S localhost:8000 2>&1 -t app &" && sleep 1; cat nohup.out
  - sleep 3
  - vendor/bin/codecept build


# Run main commands
script:
  - vendor/bin/codecept run tests/acceptance

#after_script:

#after_success:

#after_failure:


# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

