language: php

php:
  - 5.6

before_script:
  - cp .env .env
  - composer install --no-interaction
  - php artisan migrate
  - php artisan serve

script:
  - vendor/bin/codecept run tests/acceptance --steps